--datadepth=10                 
--minlevel=0                  
--neverignore                 

--context                      
--linenumbers                  
--columns                     
--cwe                         
--sarif                        

--singlethread                
--timeout=600                
--width=10                     
