matrix:
  include:
    - COMPILER: gcc
      CC: gcc
      ARCH: x86_64
    - COMPILER: clang
      CC: clang
      ARCH: x86_64

when:
  - event: pull_request

steps:
  - name: testing
    image: archlinux:latest
    directory: bootstrap
    environment:
      CC: ${CC}
      ARCH: ${ARCH}
    commands:
      - pacman -Syu --noconfirm ${COMPILER} make git
      - make
      - ./bin/traceyc index.trc -o app -Wall
