name: GCC macOS ARM64

on:
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v5

      - name: Install tools
        run: |
          brew update
          brew install gcc autoconf automake libtool pkg-config

      - name: Show environment
        run: |
          uname -a
          uname -m
          gcc-15 --version

      - name: Build and test
        run: |
          cd bootstrap
          autoreconf -fiv
          mkdir -p build
          cd build

          CC=gcc-15 \
          CXX=g++-15 \
          ../configure

          make V=1 -j 8
