name: Apple Clang macOS ARM64

on:
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v5

      - name: Show environment
        run: |
          uname -a
          uname -m
          clang --version

      - name: Build and test
        run: |
          cd bootstrap
          autoreconf -fiv
          mkdir -p build
          cd build

          CC=clang \
          CXX=clang++ \
          ../configure

          make V=1 -j 8
