name: Clang ARM64 Windows

on:
  pull_request:

jobs:
  build:
    runs-on: windows-11-vs2026-arm

    steps:
      - uses: actions/checkout@v7

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            cmake
            make
            pkgconf
            clang

      - name: Build
        shell: msys2 {0}
        run: |
          cd bootstrap

          mkdir -p build
          cd build

          cmake .. \
            -G "MSYS Makefiles" \
            -DARCH=native \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++

          cmake --build . --verbose
