name: GCC ARM64 Windows

on:
  pull_request:

jobs:
  build:
    runs-on: windows-11-vs2026-arm

    steps:
      - uses: actions/checkout@v7

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            autoconf
            automake
            libtool
            make
            pkgconf
            gcc

      - name: Build
        shell: msys2 {0}
        run: |
          cd bootstrap

          autoreconf -fiv

          mkdir -p build
          cd build

          ../configure CC=gcc CXX=g++

          make V=1 -j8
