name: Apple Clang macOS ARM64

on:
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v7

      - name: Install tools
        run: |
          brew update
          brew install cmake pkg-config

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install kconfiglib kbuild

      - name: Show environment
        run: |
          uname -a
          uname -m
          clang --version

      - name: Build and test
        run: |
          cd bootstrap
          mkdir -p build
          cd build

          cmake .. \
            -DARCH=native \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++

          cmake --build . --verbose