name: Clang ARMHF Linux GNU

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            llvm \
            cmake \
            pkg-config \
            gcc-arm-linux-gnueabihf \
            g++-arm-linux-gnueabihf

      - name: Build
        run: |
          cd bootstrap
          mkdir -p build && cd build

          cmake .. \
            -DARCH=native \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=arm \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_FLAGS="--target=arm-linux-gnueabihf" \
            -DCMAKE_CXX_FLAGS="--target=arm-linux-gnueabihf"

          cmake --build . --verbose
