name: GCC ARMHF Linux GNU

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            pkg-config \
            gcc-arm-linux-gnueabihf \
            g++-arm-linux-gnueabihf \
            python3-pip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install kconfiglib kbuild

      - name: Build
        run: |
          cd bootstrap
          mkdir -p build && cd build

          cmake .. \
            -DARCH=native \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=arm \
            -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
            -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++

          cmake --build . --verbose