name: GCC ARMHF Linux GNU

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            automake \
            autoconf \
            libtool \
            pkg-config \
            gcc-arm-linux-gnueabihf \
            g++-arm-linux-gnueabihf

      - name: Build
        run: |
          cd bootstrap

          autoreconf -fiv

          mkdir -p build
          cd build

          export CC=arm-linux-gnueabihf-gcc
          export CXX=arm-linux-gnueabihf-g++

          ../configure \
            --host=arm-linux-gnueabihf

          make V=1
