name: Clang i686 Linux GNU

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            llvm \
            gcc-i686-linux-gnu \
            g++-i686-linux-gnu \
            cmake \
            pkg-config \
            python3-pip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install kconfiglib kbuild

      - name: Build
        run: |
          cd bootstrap
          mkdir -p build && cd build

          cmake .. \
            -DARCH=native \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=i686 \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_FLAGS="--target=i686-linux-gnu" \
            -DCMAKE_CXX_FLAGS="--target=i686-linux-gnu"

          cmake --build . --verbose