name: GCC i686 Linux GNU

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            pkg-config \
            gcc-i686-linux-gnu \
            g++-i686-linux-gnu

      - name: Build
        run: |
          cd bootstrap
          mkdir -p build && cd build

          cmake .. \
            -DARCH=native \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=i686 \
            -DCMAKE_C_COMPILER=i686-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=i686-linux-gnu-g++

          cmake --build . --verbose
