name: Clang i686 Windows

on:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            autoconf
            automake
            libtool
            make
            pkgconf
            mingw-w64-x86_64-clang
            mingw-w64-i686-gcc

      - name: Build
        shell: msys2 {0}
        run: |
          export PATH="/mingw64/bin:$PATH"

          cd bootstrap

          autoreconf -fiv

          mkdir -p build
          cd build

          ../configure \
            CC="clang -m32" \
            CXX="clang++ -m32" \
            --host=i686-w64-mingw32

          make V=1 -j8
