name: Clang x86_64 Linux GNU

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm automake autoconf libtool pkg-config

      - name: Build and test
        run: |
          cd bootstrap
          autoreconf -fiv
          mkdir -p build && cd build
          CC=clang CXX=clang++ ../configure
          make V=1 -j 8
