name: GCC macOS Intel

on:
  pull_request:

jobs:
  build:
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v7

      - name: Install MacPorts
        run: |
          curl -L https://github.com/macports/macports-base/releases/download/v2.10.2/MacPorts-2.10.2-15-x86_64.pkg -o MacPorts.pkg
          sudo installer -pkg MacPorts.pkg -target /
          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
          echo "/opt/local/bin" >> $GITHUB_PATH
          echo "/opt/local/sbin" >> $GITHUB_PATH

      - name: Install tools via MacPorts
        run: |
          sudo port -v selfupdate
          sudo port install gcc15 cmake pkgconfig

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install kconfiglib kbuild

      - name: Show environment
        run: |
          uname -a
          uname -m
          gcc-15 --version

      - name: Build and test
        run: |
          cd bootstrap
          mkdir -p build
          cd build

          cmake .. \
            -DARCH=native \
            -DCMAKE_C_COMPILER=gcc-15 \
            -DCMAKE_CXX_COMPILER=g++-15

          cmake --build . --verbose