name: GCC x86_64 Free Berkeley Software Distribution

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build and Test on FreeBSD
        uses: vmactions/freebsd-vm@v1.5.7
        with:
          sync: rsync
          copyback: false
          cpu: 1
          arch: x86_64
          sync-time: true
          disable-cache: false
          cache-after-prepare: false
          usesh: true

          prepare: |
            pkg update
            pkg install -y \
              gcc \
              gmake \
              cmake \
              pkgconf

          run: |
            cd bootstrap
            mkdir -p build
            cd build

            cmake .. \
              -DARCH=native \
              -DCMAKE_C_COMPILER=gcc \
              -DCMAKE_CXX_COMPILER=g++ \
              -DCMAKE_MAKE_PROGRAM=gmake

            cmake --build . --verbose
