name: GCC macOS Intel

on:
  pull_request:

jobs:
  build:
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v7

      - name: Install tools
        run: |
          brew update
          brew install gcc cmake pkg-config

      - name: Show environment
        run: |
          uname -a
          uname -m
          gcc-15 --version

      - name: Build and test
        run: |
          cd bootstrap
          mkdir -p build
          cd build

          cmake .. \
            -DARCH=native \
            -DCMAKE_C_COMPILER=gcc-15 \
            -DCMAKE_CXX_COMPILER=g++-15

          cmake --build . --verbose
